// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Message_screen_init(void)
{
    ui_Message = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Message, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MessageToMainButton = lv_imgbtn_create(ui_Message);
    lv_imgbtn_set_src(ui_MessageToMainButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_realease__png, NULL);
    lv_imgbtn_set_src(ui_MessageToMainButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_realease__png, NULL);
    lv_obj_set_width(ui_MessageToMainButton, 48);
    lv_obj_set_height(ui_MessageToMainButton, 48);

    ui_BatteryLabel = lv_label_create(ui_Message);
    lv_obj_set_width(ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabel, 20);
    lv_obj_set_y(ui_BatteryLabel, 50);
    lv_label_set_text(ui_BatteryLabel, "Battery:");
    lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0x020101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MessageToMainButton, ui_event_MessageToMainButton, LV_EVENT_ALL, NULL);

}
