// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToOpenCVButton = lv_imgbtn_create(ui_Main);
    lv_imgbtn_set_src(ui_ToOpenCVButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_opencv_realease_png, NULL);
    lv_imgbtn_set_src(ui_ToOpenCVButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_opencv_press_png, NULL);
    lv_obj_set_width(ui_ToOpenCVButton, 64);
    lv_obj_set_height(ui_ToOpenCVButton, 64);
    lv_obj_set_x(ui_ToOpenCVButton, 20);
    lv_obj_set_y(ui_ToOpenCVButton, 20);

    ui_OpenCVLabel = lv_label_create(ui_Main);
    lv_obj_set_width(ui_OpenCVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OpenCVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OpenCVLabel, 22);
    lv_obj_set_y(ui_OpenCVLabel, 80);
    lv_label_set_text(ui_OpenCVLabel, "OpenCV");
    lv_obj_set_style_text_color(ui_OpenCVLabel, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OpenCVLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OpenCVLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToSetButton = lv_imgbtn_create(ui_Main);
    lv_imgbtn_set_src(ui_ToSetButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_set_realease_png, NULL);
    lv_imgbtn_set_src(ui_ToSetButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_set_press_png, NULL);
    lv_obj_set_width(ui_ToSetButton, 64);
    lv_obj_set_height(ui_ToSetButton, 64);
    lv_obj_set_x(ui_ToSetButton, 100);
    lv_obj_set_y(ui_ToSetButton, 20);

    ui_SetLabel = lv_label_create(ui_Main);
    lv_obj_set_width(ui_SetLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetLabel, 104);
    lv_obj_set_y(ui_SetLabel, 80);
    lv_label_set_text(ui_SetLabel, "WiFiSet");
    lv_obj_set_style_text_color(ui_SetLabel, lv_color_hex(0x18AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMessageButton = lv_imgbtn_create(ui_Main);
    lv_imgbtn_set_src(ui_ToMessageButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_message_realease_png, NULL);
    lv_imgbtn_set_src(ui_ToMessageButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_message_press_png, NULL);
    lv_obj_set_width(ui_ToMessageButton, 64);
    lv_obj_set_height(ui_ToMessageButton, 64);
    lv_obj_set_x(ui_ToMessageButton, 180);
    lv_obj_set_y(ui_ToMessageButton, 20);

    ui_MessageLabel = lv_label_create(ui_Main);
    lv_obj_set_width(ui_MessageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MessageLabel, 182);
    lv_obj_set_y(ui_MessageLabel, 80);
    lv_label_set_text(ui_MessageLabel, "Message");
    lv_obj_set_style_text_color(ui_MessageLabel, lv_color_hex(0xEE8D31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MessageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ToOpenCVButton, ui_event_ToOpenCVButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToSetButton, ui_event_ToSetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToMessageButton, ui_event_ToMessageButton, LV_EVENT_ALL, NULL);

}
