// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_OpenCV_screen_init(void)
{
    ui_OpenCV = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OpenCV, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OpenCVToMainButton = lv_imgbtn_create(ui_OpenCV);
    lv_imgbtn_set_src(ui_OpenCVToMainButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_realease__png, NULL);
    lv_imgbtn_set_src(ui_OpenCVToMainButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_press_png, NULL);
    lv_obj_set_width(ui_OpenCVToMainButton, 48);
    lv_obj_set_height(ui_OpenCVToMainButton, 48);

    ui_OpenCVDemoLabel = lv_label_create(ui_OpenCV);
    lv_obj_set_width(ui_OpenCVDemoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OpenCVDemoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OpenCVDemoLabel, 100);
    lv_obj_set_y(ui_OpenCVDemoLabel, 20);
    lv_label_set_text(ui_OpenCVDemoLabel, "OpenCV Demo");
    lv_obj_set_style_text_color(ui_OpenCVDemoLabel, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OpenCVDemoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OpenCVToMainButton, ui_event_OpenCVToMainButton, LV_EVENT_ALL, NULL);

}
