// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Set_screen_init(void)
{
    ui_Set = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Set, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetToMainButton = lv_imgbtn_create(ui_Set);
    lv_imgbtn_set_src(ui_SetToMainButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_realease__png, NULL);
    lv_imgbtn_set_src(ui_SetToMainButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_press_png, NULL);
    lv_obj_set_width(ui_SetToMainButton, 48);
    lv_obj_set_height(ui_SetToMainButton, 48);

    ui_WiFiScanRoller = lv_roller_create(ui_Set);
    lv_roller_set_options(ui_WiFiScanRoller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_WiFiScanRoller, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_WiFiScanRoller, 285);
    lv_obj_set_height(ui_WiFiScanRoller, 149);
    lv_obj_set_x(ui_WiFiScanRoller, 0);
    lv_obj_set_y(ui_WiFiScanRoller, -5);
    lv_obj_set_align(ui_WiFiScanRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_WiFiScanRoller, &ui_font_AlimamaShuHeiTi_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WiFiScanRoller, lv_color_hex(0x18AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiScanRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WiFiScanRoller, lv_color_hex(0x18AAAC), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiScanRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_IPAddrLabel = lv_label_create(ui_Set);
    lv_obj_set_width(ui_IPAddrLabel, 240);
    lv_obj_set_height(ui_IPAddrLabel, 20);
    lv_obj_set_x(ui_IPAddrLabel, 10);
    lv_obj_set_y(ui_IPAddrLabel, -93);
    lv_obj_set_align(ui_IPAddrLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_IPAddrLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_IPAddrLabel, "Connect:TP-LINK_417,IP:192.168.1.140");
    lv_obj_set_style_text_color(ui_IPAddrLabel, lv_color_hex(0x18AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPAddrLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPAddrLabel, &ui_font_AlimamaShuHeiTi_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiFreshButton = lv_btn_create(ui_Set);
    lv_obj_set_width(ui_WiFiFreshButton, 70);
    lv_obj_set_height(ui_WiFiFreshButton, 40);
    lv_obj_set_x(ui_WiFiFreshButton, -70);
    lv_obj_set_y(ui_WiFiFreshButton, 95);
    lv_obj_set_align(ui_WiFiFreshButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiFreshButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiFreshButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiFreshButton, lv_color_hex(0x18AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiFreshButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiFreshLabel = lv_label_create(ui_WiFiFreshButton);
    lv_obj_set_width(ui_WiFiFreshLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiFreshLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiFreshLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiFreshLabel, "Fresh");

    ui_WiFiConnectButton = lv_btn_create(ui_Set);
    lv_obj_set_width(ui_WiFiConnectButton, 70);
    lv_obj_set_height(ui_WiFiConnectButton, 40);
    lv_obj_set_x(ui_WiFiConnectButton, 70);
    lv_obj_set_y(ui_WiFiConnectButton, 95);
    lv_obj_set_align(ui_WiFiConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiConnectButton, lv_color_hex(0x18AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnectLabel = lv_label_create(ui_WiFiConnectButton);
    lv_obj_set_width(ui_WiFiConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiConnectLabel, "Connect");

    ui_WiFiKeyboard = lv_keyboard_create(ui_Set);
    lv_obj_set_width(ui_WiFiKeyboard, 300);
    lv_obj_set_height(ui_WiFiKeyboard, 120);
    lv_obj_set_align(ui_WiFiKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WiFiKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_WiFiKeyboard, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiKeyboard, lv_color_hex(0x1A80CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiEnterPassPanel = lv_obj_create(ui_Set);
    lv_obj_set_width(ui_WiFiEnterPassPanel, 186);
    lv_obj_set_height(ui_WiFiEnterPassPanel, 64);
    lv_obj_set_x(ui_WiFiEnterPassPanel, 0);
    lv_obj_set_y(ui_WiFiEnterPassPanel, -45);
    lv_obj_set_align(ui_WiFiEnterPassPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiEnterPassPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WiFiEnterPassPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_WiFiEnterPassPanel, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiEnterPassPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiPassTextArea = lv_textarea_create(ui_WiFiEnterPassPanel);
    lv_obj_set_width(ui_WiFiPassTextArea, 190);
    lv_obj_set_height(ui_WiFiPassTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_WiFiPassTextArea, 0);
    lv_obj_set_y(ui_WiFiPassTextArea, 12);
    lv_obj_set_align(ui_WiFiPassTextArea, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_WiFiPassTextArea, "Enter password...");
    lv_textarea_set_one_line(ui_WiFiPassTextArea, true);
    lv_obj_set_style_text_font(ui_WiFiPassTextArea, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WiFiPassTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiPassTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WiFiPassTextArea, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiSSIDLabel = lv_label_create(ui_WiFiEnterPassPanel);
    lv_obj_set_width(ui_WiFiSSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiSSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiSSIDLabel, 0);
    lv_obj_set_y(ui_WiFiSSIDLabel, -16);
    lv_obj_set_align(ui_WiFiSSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiSSIDLabel, "SSID");
    lv_obj_set_style_text_font(ui_WiFiSSIDLabel, &ui_font_AlimamaShuHeiTi_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnectWaitSpinner = lv_spinner_create(ui_Set, 1000, 90);
    lv_obj_set_width(ui_WiFiConnectWaitSpinner, 80);
    lv_obj_set_height(ui_WiFiConnectWaitSpinner, 80);
    lv_obj_set_align(ui_WiFiConnectWaitSpinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiConnectWaitSpinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WiFiConnectWaitSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_SetToMainButton, ui_event_SetToMainButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiFreshButton, ui_event_WiFiFreshButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiConnectButton, ui_event_WiFiConnectButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_WiFiKeyboard, ui_WiFiPassTextArea);
    lv_obj_add_event_cb(ui_WiFiKeyboard, ui_event_WiFiKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Set, ui_event_Set, LV_EVENT_ALL, NULL);

}
